services:
  mariadb:
    build:
      context: ./requirements/mariadb
      dockerfile: Dockerfile
    image: mariadb:inception
    env_file:
      - .env
    volumes:
      - mariadb_data:/var/lib/mysql
    networks:
      - inception_network
    container_name: mariadb
    restart: always
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "--silent"]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 30s

  wordpress:
    build:
      context: ./requirements/wordpress
      dockerfile: Dockerfile
    image: wordpress:inception
    env_file:
      - .env
    volumes:
      - wordpress_html:/var/www/html
    networks:
      - inception_network
    depends_on:
      mariadb:
        condition: service_healthy
    container_name: wordpress
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "ss -tln | grep -q ':9000'"]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 60s

  nginx:
    build:
      context: ./requirements/nginx
      dockerfile: Dockerfile
    image: nginx:inception
    env_file:
      - .env
    ports:
      - "443:443"
    volumes:
      - wordpress_html:/var/www/html
    networks:
      - inception_network
    depends_on:
      mariadb:
        condition: service_healthy
      wordpress:
        condition: service_healthy
      front-page:
        condition: service_healthy
    container_name: nginx
    restart: always
    healthcheck:
      test: ["CMD", "curl", "-k", "-f", "https://localhost"]
      timeout: 5s
      retries: 3
      start_period: 60s

  front-page:
    build:
      context: ./requirements/front-page
      dockerfile: Dockerfile
    image: front-page:inception
    networks:
      - inception_network
    container_name: front-page
    restart: always
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080"]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 20s

volumes:
  mariadb_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/ihadj/data/mariadb
  wordpress_html:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/ihadj/data/wordpress

networks:
  inception_network:
    driver: bridge